### ISSUE TITLE
App crashes when opening any repl (Mac)

### ISSUE THREAD

**Issue by wolfembers** [repl-it-discord/repl.it-electron#18]
Hello, I just updated to the latest version (1.0.2) and while the app opens fine, opening any repl instantly crashes the app.

Interestingly, it will _rarely_ open the repl without crashing, but returning to the "my repls" section and attempting to open another repl crashes the app. This behavior only occurs if I don't resize the window when I start the app. If I "fullscreen" the app (drag the corners to the corners, I like the taskbar being there) then it will crash when opening any repl the first time.

**Comment by EanKeen** [comment]
Hi! Thank you for creating an issue! I don't have a Mac so I can't check it out at the moment, but @leon332157 does and can check it out this issue when ready.

**Comment by leon332157** [comment]
Hi thanks for reporting! Is there any visible errors u can see? If not could u please execute the executable in the terminal and post the console outputs?

**Comment by leon332157** [comment]
Hi. I have successfully recreated the bug on a school computer. Sub Window works, but when I send the Sub Window into main window. The app freezes. Still trying to find out why.

**Comment by wolfembers** [comment]
Hello, when I encounter this bug I see no visible errors. Just plain crashes. Also I have very little knowledge of terminal, mainly a windows guy, so I have no idea how to execute it from terminal.

**Comment by leon332157** [comment]
And Yes, I have also successfully re-created the bug on mac os. It seems to be a problem with electron itself.

**Comment by wolfembers** [comment]
Thanks for investigating! I'll go ahead and close this and wait for the bug to be fixed.
