### ISSUE TITLE
Constant Prompts asking to open link in an external window

### ISSUE THREAD

**Issue by EanKeen** [repl-it-discord/repl.it-electron#19]
When simply opening the password and signing in with Google, the page becomes blank. However after opening a new subWindow, I can see my repls. I click on one and a popup appears with the title "Confirm External Link". It has the contents "about:blank Looks like an external link, would you like to load it externally?". This pops up about every few seconds and do not seem to disappear until exit the sub window.

When I do exit the subWindow, I get the following error:
Uncaught Exception: Error Object has been destroyed at Function <anonymous>. (C:/Users/.../main.js:848:35)

Not sure what could be the cause of this behavior, but I have some photographs below.
![image](https://user-images.githubusercontent.com/24364012/53579237-0fbba180-3b2e-11e9-8c00-11a183e1c8fc.png)
![image](https://user-images.githubusercontent.com/24364012/53579709-ed765380-3b2e-11e9-9fe8-d80a1bf9011f.png)

**Comment by leon332157** [comment]
Roger that. The bug fix seems defective, needed to double check.

**Comment by leon332157** [comment]
Thank you, this has been fixed in #20
